[package]
name = 'Supervlabs'
version = '1.0.0'

[addresses]
apto_orm = "0xfacedd48d64a2ee04cbdf5c17608bd7a5ea9144fa1fe65320c588fffea131de3"
supervlabs = "0x5c74215826f8cb2cc3861fee25969d0da5efc8d0eb055271de437446a3f62590"
package_creator = "0xbbb305f2a726977910d9222221a5ebbd1c61f570562df2a4f2a31b826c59c498"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "randomnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token", rev = "randomnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects", rev = "randomnet" }
AptoORM = { git = "https://github.com/supervlabs/apto_orm", subdir = "move/apto_orm", rev = "randomnet" }
